config/routes.rb
Rails.application.routes.draw do

  root "sessions#index"
  get '/how_to' => "sessions#how_to"
  get "/auth/:provider/callback" => "sessions#create"

  post "/create_avatar" => "users#create_avatar"
  post "/chatrooms" => "chatrooms#create"
  post "/messages" => "messages#create"
  get "/messages" => "messages#index"
  get "/chatrooms" => "chatrooms#index"
  get "/get_messages" => "chatrooms#get_messages"
  get "/chatrooms/search" => "chatrooms#search"
  get "/chatrooms/:name" => "chatrooms#show"
  get "/register" => "users#register"

	get "/signout" => "sessions#destroy"

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base

  has_many :messages, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  after_create :convert_name

  # Converting name regexes so there are no spaces or certain punctuation for Room-Name URL
  def convert_name
    self.update(name: self.name.gsub(/\s+/,"_"))
    self.update(name: self.name.gsub(",","_"))
    self.update(name: self.name.gsub(/"/,"'"))
    self.update(name: self.name.gsub(".","(dot)"))
  end

  # Destroys chatrooms and all their messages
  def timed_destroy
    if (Time.now.getgm - self.created_at.getgm) >= 86400
      self.destroy
    end
  end

  def how_old?
    creation = self.created_at.getgm
    seconds = Time.now.getgm - creation
    hours = 24 - (seconds/3600)
    minutes = 60 - ((seconds/60) % 60)
    return "#{hours.floor} hours, #{minutes.floor} minutes left"
  end

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user
  belongs_to :chatroom

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :messages
  validates_presence_of :username, :token
  validates_uniqueness_of :username, :token

  #ASW S3 request
  def self.new_aws_request
    return AWS::S3.new(:access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'])
  end

  #Grabbing current user's avatars from S3
  def self.get_avatars(username)
    result = {}
    emotions = ["happy", "sad", "mad", "omg", "lol", "wat"]
    aws = User.new_aws_request
    bucket = aws.buckets[ENV['S3_BUCKET_NAME']]

    emotions.each { |emotion| result[emotion] = bucket.objects["#{username}_#{emotion}.png"] }
    return result
  end

  def get_avatar(emotion)
    aws = User.new_aws_request
    bucket = aws.buckets[ENV['S3_BUCKET_NAME']]
    return bucket.objects["#{self.username}_#{emotion}.png"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user

  private

  #checking for user signed in
  def signed_in?
    true if session[:oauth_token]
  end

  #current user object return
  def current_user
  	if signed_in?
  		User.find_by(username: session[:username])
  	else
  		redirect_to root_path
  	end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  before_action :current_user

  def index
    begin
      @chatroom = Chatroom.new

      #AJAX request for rooms participated in
      rooms_ids = current_user.messages.pluck(:chatroom_id).uniq.sort!
      rooms = rooms_ids.map { |id| Chatroom.find(id) }
      @recent_rooms = {}
      rooms.each do |room|
        @recent_rooms[room.name] = room.how_old?
      end
      updated_rooms = @recent_rooms.map do |room_name, time_left|
        new_array = []
        new_array.push(room_name, time_left)
      end

      #Grabbing current user's Avatars from S3
      @avatars = User.get_avatars(current_user.username)
    rescue
      redirect_to register_path
    end

    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: updated_rooms.to_json }
    end
  end

  def search
    room_name = params[:search].gsub(/\s+/,"_").gsub(",","_").gsub(/"/,"'").gsub(".","(dot)")
    @chatroom = Chatroom.find_by(name: room_name)
    if @chatroom
      redirect_to "/chatrooms/#{@chatroom.name}"
    else
      redirect_to chatrooms_path, notice: "Room: '#{params[:search]}' doesn't seem to exist - try creating it!"
    end
  end

  def create
    @chatroom = Chatroom.create(chatroom_params)
    if @chatroom.save
      redirect_to "/chatrooms/#{@chatroom.name}"
    else
      redirect_to chatrooms_path, notice: "Room: '#{@chatroom.name}' already exists - try searching for it!"
    end
  end

  def show
    begin
      @avatars = User.get_avatars(current_user.username)
      @chatroom = Chatroom.find_by(name: params[:name])
      @messages = @chatroom.messages.order(created_at: :desc)
    rescue
      redirect_to chatrooms_path
    end
  end

  def get_messages
    chatroom = Chatroom.find_by(name: params[:name])
    messages = chatroom.messages.order(id: :desc)

    #AJAX request for user message ranking system in a chatroom
    users = []
    messages.each { |msg| users << msg.user.username }
    users = users.uniq
    user_msg_count = users.map do |usr|
      User.find_by(username: usr).messages.where(chatroom_id: chatroom.id).size
    end
    ranking_data = users.zip(user_msg_count)

    #AJAX request for new messages in chatroom - need to fix by ID instead of time value
    new_msgs = []
    messages.each do |msg|
      if msg.id > params[:msg_id].to_i && msg.user.username != current_user.username
        new_msgs << { message: msg, avt: msg.user.get_avatar(msg.emotion).read, msg_id: msg.id }
      end
    end

    #Returned AJAX object
    return_data = {
      user: current_user.username,
      rankings: ranking_data,
      newMsgs: new_msgs
    }

    respond_to do |format|
      format.json { render json: return_data.to_json }
    end
  end

  private

  def chatroom_params
    return params[:chatroom].permit(:name)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :current_user

  def create
    @chatroom = Chatroom.find_by(name: params[:room_name])
    emotions = %w(#happy #sad #mad #omg #lol #wat)
    emotion = params[:content].scan(/(#\w*)/).flatten.first
    if emotion.nil? || emotions.include?(emotion) == false
      emotion = 'happy'
    end
    new_content = params[:content].gsub(' ' + emotion, '')
    message = @chatroom.messages.create(content: new_content, chatroom_id: @chatroom.id, user_id: current_user.id, emotion: emotion.gsub('#', ''))
    return_data = {obj: message, user: current_user.username, msg_id: message.id}

    respond_to do |format|
      format.html { redirect_to "/chatrooms/#{@chatroom.name}" }
      format.json { render json: return_data.to_json }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    # redirect_to "/chatrooms" if signed_in?
  end
  
  #Logging in via Twitter Oauth
  def create
  	auth = request.env["omniauth.auth"]
    session[:oauth_token] = auth.credentials.token
    session[:oauth_token_secret] = auth.credentials.secret
    session[:username] = auth.extra.access_token.params[:screen_name]

    if User.exists?(username: session[:username]) == false
    	User.create(username: session[:username], token: session[:oauth_token])
      redirect_to register_path, :notice => "Welcome to Chat.ly!"
    else
      redirect_to chatrooms_path, :notice => "Welcome back #{session[:username]}!"
    end
  end

  def destroy
    session[:username] = nil
    session[:oauth_token] = nil
    redirect_to root_path
  end

  def how_to

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :current_user

	#Photo taking
	def register
		flash[:notice] = "Get ready to take your avatar photos! Make sure to allow access to your webcam!"
	end

	#creating avatars and storing directly into AWS S3
	def create_avatar
		s3 =  User.new_aws_request
		bucket = s3.buckets[ENV['S3_BUCKET_NAME']]
		bucket.acl = :public_read
		data = params[:file]
		file_name = "#{current_user.username}_#{params[:emotion]}.png"
		bucket.objects.create(file_name, data)
		return_data = {file: data, emotion: params[:emotion]}

		respond_to do |format|
			format.json { render json: return_data.to_json }
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_form.html.erb
<%= form_for(@chatroom) do |f| %>

  <div class="new_form">
    <%= f.text_field :name %>
	  <%= f.submit "Create", :class => 'button' %>
  </div>

<% end %>

app/views/chatrooms/_search.html.erb
<%= form_tag('/chatrooms/search', :method => "get") do %>

  <div class="search_form">
    <%= text_field_tag :search %>
  	<%= submit_tag "Search", :class => 'button' %>
  </div>

<% end %>

app/views/chatrooms/index.html.erb
<div class="left_col">
  <h3>Hey <span class="username"><%= current_user.username %></span>!</h3>
  <hr>
  <h4 class="notice"><%= flash[:notice] %></h4>
  <div class="avatar_box top-padding">
    <% @avatars.each do |emo, img| %>
    <div class="avatar-label">
      <div class="avatar"><img src="<%= img.read %>" id="<%= current_user.username %>_<%= emo %>"></div>
      <div class="label">#<%= emo %></div>
    </div>
    <% end %>
  </div>
  <p class="center">Feel like going with a different face today? Retake your avatars and surprise your friends!! <%= link_to "Retake Avatars", register_path, :class => "button" %></p>

  <div class="chat-index">
    <div class="form-box left">
      <h3>Create a Chatroom</h3>
      <%= render "form" %>
    </div>
    <p class="left">OR</p>
    <div class="form-box right">
      <h3>Enter a Chatroom</h3>
      <%= render "search" %>
    </div>
    <div class="clear"></div>
  </div>
</div>
<div class="right_col">
  <div class="recent_rooms">
    <h3>Recent Rooms</h3>
    <hr>
    <ul class="room_list">
      <% @recent_rooms.each do |room_name, time_left| %>
      <li class="room_list_text"><span class="left"><i class="fa fa-bookmark"></i><%= link_to "#{room_name} :", "/chatrooms/#{room_name}" %></span><span class="right"><%= "#{time_left}" %></span></li>
      <li class="clear"></li>
      <% end %>
    </ul>
  </div>
</div>
<div class="clear"></div>

<%= javascript_tag do %>
setInterval(recentRoomTimes, 45000);
<% end %>

app/views/chatrooms/show.html.erb
<div class="left_col">

  <div class="avatar_box">
    <% @avatars.each do |emo, img| %>
    <div class="avatar-label">
      <div class="avatar"><img src="<%= img.read %>" id="<%= current_user.username %>_<%= emo %>"></div>
      <div class="label">#<%= emo %></div>
    </div>
    <% end %>
  </div>

  <div class="message-form">
    <input type="text" id="new-message">
    <button id="send-button">Send</button>
  </div>

  <div class="chat-box">
  <% @messages.each do |msg| %>
    <div class="message-box left" id="<%= msg.user.username %>" msg_id="<%= msg.id %>">
      <div class="message-avatar avatar">
        <img src='<%= msg.user.get_avatar(msg.emotion).read %>'>
      </div>
      <div class="message-content">
        <div class="arrow_box"><%= msg.content %></div>
      </div>
    </div>
    <div class="clear"></div>
  <% end %>
  </div>

</div>
<div class="right_col">
  <h3><i class="fa fa-trophy"></i>Top Contributors</h3>
  <hr>
  <div class="ranked_users" id="ranking_box"></div>
</div>


<%= javascript_tag do %>
  msgLayout("<%= j(current_user.username) %>");
  setInterval(grabMessages, 2500);
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>emochat</title>
  <link rel="icon" type="image/png" href="http://i.imgur.com/mCtiV8I.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="fixed_header">
    <div class="header_content">
      <div class="logo">
        <h1><%= link_to "emochat", root_path %> <%= "chatroom: " + @chatroom.name if params[:action] == 'show' %></h1>
      </div>
      <ul class="nav">
        <li><i class="fa fa-info-circle"></i><%= link_to "Users Guide", how_to_path %></li>
        <li><i class="fa fa-user"></i><%= link_to "Account", chatrooms_path %></li>
        <li><i class="fa fa-sign-out"></i><%= link_to "Sign Out", signout_path %></li>
      </ul>
    </div>
  </div>

  <div class="wrap">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/register.html.erb
<h1>Register your Avatars!</h1>
<h4 class="notice"><%= flash[:notice] %></h4>
<div id="photo-area">
	<div class="photo-left">
		<video id="player" autoplay="true"></video>
		<canvas id="canvas"></canvas>
	</div>
	<div class="photo-right">
    
	</div>
</div>
<div class="buttons">
<p id="status"></p>
<button id="startbutton">Take photo</button>
</div>
<div class="clear"></div>
<%= javascript_tag do %>
	webCam();
<% end %>